require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/labels", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Label. As you add validations to Label, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Label.create! valid_attributes
      get labels_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      label = Label.create! valid_attributes
      get label_url(label)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_label_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      label = Label.create! valid_attributes
      get edit_label_url(label)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Label" do
        expect {
          post labels_url, params: { label: valid_attributes }
        }.to change(Label, :count).by(1)
      end

      it "redirects to the created label" do
        post labels_url, params: { label: valid_attributes }
        expect(response).to redirect_to(label_url(Label.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Label" do
        expect {
          post labels_url, params: { label: invalid_attributes }
        }.to change(Label, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post labels_url, params: { label: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested label" do
        label = Label.create! valid_attributes
        patch label_url(label), params: { label: new_attributes }
        label.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the label" do
        label = Label.create! valid_attributes
        patch label_url(label), params: { label: new_attributes }
        label.reload
        expect(response).to redirect_to(label_url(label))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        label = Label.create! valid_attributes
        patch label_url(label), params: { label: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested label" do
      label = Label.create! valid_attributes
      expect {
        delete label_url(label)
      }.to change(Label, :count).by(-1)
    end

    it "redirects to the labels list" do
      label = Label.create! valid_attributes
      delete label_url(label)
      expect(response).to redirect_to(labels_url)
    end
  end
end
